import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import ReactQueryClientProvider from "@/components/ReactQueryClientProvider"
import "./globals.css"

import { cn } from "@/lib/utils"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("bg-background font-sans antialiased", fontSans.variable)}
      >
        <ReactQueryClientProvider>
          <main className="flex flex-col items-center justify-center p-24 min-h-screen">
            {children}
          </main>
        </ReactQueryClientProvider>
      </body>
    </html>
  )
}
